"""User: name -> username

Revision ID: 058aa74ec84d
Revises: 65c09560a30c
Create Date: 2022-12-09 22:14:26.035642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '058aa74ec84d'
down_revision = '65c09560a30c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('usernamename', sa.String(length=32), nullable=True))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('user', 'usernamename')
    # ### end Alembic commands ###
