"""user id -> userid

Revision ID: 1dfc2a6e016e
Revises: 9272949191d1
Create Date: 2022-03-29 21:54:57.029735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1dfc2a6e016e'
down_revision = '9272949191d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('userid', sa.Integer(), nullable=False))
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_column('user', 'userid')
    # ### end Alembic commands ###
