"""fixed typo

Revision ID: 720ac58177d8
Revises: 058aa74ec84d
Create Date: 2022-12-09 22:21:56.325483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '720ac58177d8'
down_revision = '058aa74ec84d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=32), nullable=True))
    op.drop_column('user', 'usernamename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('usernamename', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
