"""Added user model, but for real this time

Revision ID: 9272949191d1
Revises: 099a27b88983
Create Date: 2022-03-29 21:49:25.881976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9272949191d1'
down_revision = '099a27b88983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=102), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('index', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('response_time', mysql.FLOAT(), nullable=True),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('method', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=True),
    sa.Column('size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=True),
    sa.Column('user_agent', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=True),
    sa.Column('remote_address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=True),
    sa.Column('exception', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=True),
    sa.Column('referrer', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=True),
    sa.Column('browser', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=True),
    sa.Column('platform', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=True),
    sa.Column('mimetype', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=True),
    sa.PrimaryKeyConstraint('index'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user')
    # ### end Alembic commands ###
