"""update User

Revision ID: 93be00ae91df
Revises: 34f09aa9764e
Create Date: 2022-12-09 18:30:44.095648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93be00ae91df'
down_revision = '34f09aa9764e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=32), nullable=True))
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('first_name', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
